# Generated by Django 3.2.2 on 2021-06-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.site')),
            ],
        ),
    ]
