# Generated by Django 3.2.2 on 2021-06-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='thumb_img',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Wikipedia-logo-v2.svg/800px-Wikipedia-logo-v2.svg.png'),
        ),
    ]
